import { t } from 'i18next';
import { StyleSheet, StatusBar, Platform } from 'react-native';
const statusHeight = StatusBar.currentHeight;

export default (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.primary,
      paddingBottom: 30,
    },

    closeButton: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 60 : 40,
      width: 30,
      height: 30,
      right: 20,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.colors.screenBackgroundSecondary,
      borderRadius: 50,
      padding: 2,
      opacity: 0.5,
      zIndex: 999,
    },
    titleIcon: {
      color: theme.colors.white,
    },
    headerWrapper: {
      marginLeft: 10,
    },
    imageText: {
      fontSize: 12,
      position: 'absolute',
      bottom: 5,
      left: 10,
      color: 'white',
      fontWeight: 'normal',
      zIndex: 2,
      ...{ ...theme.darkShadow },
    },
    contentList: {
      marginTop: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bodyWrapper: {
      flex: 1,
    },
    listIcon: {
      color: theme.colors.blackWhite,
    },
    offersContainer: {
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 5,
      flex: 1,
      minHeight: '40%',
    },
    offer: {
      alignItems: 'center',
      marginHorizontal: 5,
      marginVertical: 10,
      borderRadius: 10,
      minHeight: 110,
      minWidth: theme.windowWidth / 2.3,
      flexDirection: 'column',
      paddingTop: 14,
      paddingHorizontal: 10,
      ...{ ...theme.softShadow },
      backgroundColor: theme.colors.cardBackground,
      borderColor: theme.colors.notch,
      borderWidth: 2,
    },
    offerBadge: {
      position: 'absolute',
      zIndex: 99,
      top: 2,
      right: 20,
      backgroundColor: theme.colors.blue,
      borderRadius: 8,
      paddingHorizontal: 5,
      paddingVertical: 2,
    },
    offerBadge2: {
      position: 'absolute',
      zIndex: 99,
      top: 2,
      left: 20,
      backgroundColor: theme.colors.orange,
      borderRadius: 8,
      paddingHorizontal: 5,
      paddingVertical: 2,
    },
    badgeText: {
      color: theme.colors.white,
      fontFamily: theme.font3,
      fontWeight: 'bold',
      fontSize: 11.5,
    },
    selectedOffer: {
      borderWidth: 4,
      borderColor: theme.colors.purple,
    },
    subText: {
      // ...{...theme.title},
      fontFamily: theme.font3,
      fontSize: 14,
      fontWeight: 'normal',
      color: theme.colors.blackWhite,
      marginLeft: 1,
    },
    price: {
      marginVertical: 5,
      ...{ ...theme.title },
      color: theme.colors.black,
      fontSize: 15,
    },
    selectedPrice: {
      color: theme.colors.purple,
    },
    oldPrice: {
      color: theme.colors.iconDark,
      textDecorationLine: 'line-through',
      textDecorationColor: theme.colors.red,
      fontSize: 14,
      bottom: -4,
    },
    priceWrapper: {
      flexDirection: 'column',
      marginTop: -15,
      marginBottom: 15,
    },
    smallText: {
      fontSize: 12,
    },
    buttonView: {
      position: 'absolute',
      bottom: 13,
      height: 120,
      width: '100%',
      backgroundColor: 'transparent',
      zIndex: 999,
      justifyContent: 'flex-start',
      alignItems: 'center',
      paddingTop: 5,
    },
    buttonFooterView: {
      position: 'absolute',
      height: 115,
      width: '100%',
      backgroundColor: 'transparent',
      justifyContent: 'flex-start',
      alignItems: 'center',
      bottom: theme.hasNotch ? -50 : -80,
    },
    footerText: {
      color: theme.colors.white,
      textAlign: 'center',
      fontSize: 15,
      marginTop: 10,
      marginBottom: 10,
    },
    footerIcon: {
      color: theme.colors.white,
      fontSize: 14,
    },
    footerTextLink: {
      textDecorationLine: 'underline',
      ...{ ...theme.subText },
      color: theme.colors.placeholderInput,
      textAlign: 'center',
      fontSize: 13,
      marginTop: 2,
      zIndex: 999,
    },
    footerLinkView: {
      flexDirection: 'row',
    },
    footerLink: {
      marginHorizontal: 5,
    },
    periodText: {
      fontSize: 14,
    },
    buttonTextUp: {
      ...{ ...theme.subText },
      color: theme.colors.blackWhite,
      fontSize: 13,
      position: 'absolute',
      marginTop: -16,
      ...{ ...theme.blueShadow },
    },
    linearGradient: {},
    offerItem: {},
    checkMarkWrapper: {
      backgroundColor: theme.colors.white,
      width: 25,
      height: 25,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 5,
      marginVertical: 2,
    },
    checkMark: {
      color: theme.colors.black,
      fontSize: 18,
    },
    iconTextItem: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '50%',
    },
    listItemText: {
      fontFamily: theme.font3,
      fontSize: 16,
      color: theme.colors.white,
      fontWeight: 'bold',
    },
    monthlyPrice: {
      fontSize: 16,
      marginTop: -5,
      marginBottom: 5,
    },
    title: {
      ...{ ...theme.title },
      fontSize: 18,
      marginTop: 3,
      marginBottom: -5,
      color: theme.colors.blackWhite,
    },
    selectedOfferTitle: {
      color: theme.colors.purple,
      fontSize: 22,
    },
    trialText: {
      color: theme.colors.white,
      fontSize: 14,
    },
    headerVideo: {
      width: '50%',
      height: theme.windowHeight / 3,
      alignSelf: 'center',
      marginTop: 50,
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      borderRadius: 35,
      borderBottomEndRadius: 35,
      borderBottomStartRadius: 35,
      zIndex: 2,
    },
    headerVideoLeft: {
      right: 10,
      transform: [{ rotate: '-20deg' }],
    },
    headerVideoRight: {
      left: theme.windowWidth - (theme.windowWidth * 40) / 100,
      transform: [{ rotate: '20deg' }],
    },
    rightLeftCommonVideo: {
      zIndex: 1,
      opacity: 0.5,
      top: 25,
      position: 'absolute',
      width: '40%',
      height: theme.windowHeight / 3.8,
    },

    scrollView: {
      flex: 1,
    },
    headerSection: {
      alignItems: 'center',
      marginTop: 100,
      marginBottom: 30,
    },
    headerTitle: {
      fontSize: 32,
      fontWeight: 'bold',
      color: theme.colors.white,
      marginBottom: 15,
    },
    headerBadge: {
      borderRadius: 25,
      marginTop: 15,
    },
    headerBadgeText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
      margin: 15,
    },
    benefitsSection: {
      paddingHorizontal: 20,
      marginTop: 20,
      alignItems: 'center',
      width: '100%',
      maxWidth: 350,
      alignSelf: 'center',
    },
    benefitItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 25,
      width: '100%',
    },
    benefitIconWrapper: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: theme.colors.white,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
    },
    benefitIcon: {
      fontSize: 20,
      color: theme.colors.black,
    },
    benefitTextWrapper: {
      flex: 1,
    },
    benefitTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.colors.white,
      marginBottom: 4,
    },
    benefitSubtitle: {
      fontSize: 14,
      color: theme.colors.gray,
    },
  });
